server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: API-GW
  cloud:
    gateway:
      routes:
        - id: MEMBER-API
          uri: lb://MEMBER-API
          predicates:
            - Path=/user/**
        - id: MOVIE-API
          uri: lb://MOVIE-API
          predicates:
            - Path=/movie/**
