server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://kpaas-discovery-service-1:8761/eureka
spring:
  application:
    name: API-GW
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
              
      routes:
        - id: MEMBER-API
          uri: lb://MEMBER-API
          predicates:
            - Path=/member/profile
          filters:
            - name: JwtAuthentication
              args: 
                headerName: Authorization
                granted: Bearer
        
        - id: MEMBER-API
          uri: lb://MEMBER-API
          predicates:
            - Path=/nick_name
          filters:
            - name: JwtAuthentication
              args: 
                headerName: Authorization
                granted: Bearer
        - id: MEMBER-API
          uri: lb://MEMBER-API
          predicates:
            - Path=/member/profile/other/**
          filters:
            - name: JwtAuthentication
              args: 
                headerName: Authorization
                granted: Bearer
        - id: MEMBER-API
          uri: lb://MEMBER-API
          predicates:
            - Path=/member/logout/**
          filters:
            - name: JwtAuthentication
              args: 
                headerName: Authorization
                granted: Bearer
        - id: MEMBER-API
          uri: lb://MEMBER-API
          predicates:
            - Path=/member/payments/**
          filters:
            - name: JwtAuthentication
              args: 
                headerName: Authorization
                granted: Bearer
        - id: MEMBER-API
          uri: lb://MEMBER-API
          predicates:
            - Path=/member/**
        - id: MEMBER-API
          uri: lb://MEMBER-API
          predicates:
            - Path=/oauth2/**
        - id: MEMBER-API
          uri: lb://MEMBER-API
          predicates:
            - Path=/follow
          filters:
            - name: JwtAuthentication
              args: 
                headerName: Authorization
                granted: Bearer
        - id: MEMBER-API
          uri: lb://MEMBER-API
          predicates:
            - Path=/follow/follower/**
          
        - id: MEMBER-API
          uri: lb://MEMBER-API
          predicates:
            - Path=/follow/following/**
        
        - id: POST-API
          uri: lb://PRODUCT-API
          predicates:
            - Path=/post/page
        
        - id: POST-API
          uri: lb://POST-API
          predicates:
            - Path=/post/search/**
        - id: POST-API
          uri: lb://POST-API
          predicates:
            - Path=/post/mypage
        - id: POST-API
          uri: lb://POST-API
          predicates:
            - Path=/post/profile/like/**
        - id: POST-API
          uri: lb://POST-API
          predicates:
            - Path=/post/detail
        - id: POST-API
          uri: lb://POST-API
          predicates:
            - Path=/post/like/**
          filters:
            - name: JwtAuthentication 
              args: 
                headerName: Authorization
                granted: Bearer
        - id: POST-API
          uri: lb://POST-API
          predicates:
            - Path=/post/**
          filters:
            - name: JwtAuthentication
              args: 
                headerName: Authorization
                granted: Bearer
        - id: PURCHASE-API
          uri: lb://PURCHASE-API
          predicates:
            - Path=/payments/**
          filters:
            - name: JwtAuthentication 
              args: 
                headerName: Authorization
                granted: Bearer
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
