server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://movie-discovery-service-1:8761/eureka
spring:
  application:
    name: API-GW
  cloud:
    gateway:
      routes:
        - id: MEMBER-API
          uri: lb://MEMBER-API
          predicates:
            - Path=/member/**
            - Path=/oauth2/**
            - Path=/follow/**
        - id: MOVIE-API
          uri: lb://PRODUCT-API
          predicates:
            - Path=/product/**
