server:
  port: 5080
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
        uri: mongodb://localhost:27017/test?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.10
  application:
    name: chat-api

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
