server:
  port: 6080
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://purchase-db:3307/paymentandpointdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
  application:
    name: purchase
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
