server:
  port: 6080h
spring:
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://purchase-db:3306/paymentandpointdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

